AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
  NewCops: enable

Lint/MissingSuper:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Metrics/MethodLength:
  Max: 20
